//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web07.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web07.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nên sớm hơn ngày hiện tại..
        /// </summary>
        public static string Error_DateEarly {
            get {
                return ResourceManager.GetString("Error_DateEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh phải sớm hơn ngày hiện tại..
        /// </summary>
        public static string Error_DateOfBirth {
            get {
                return ResourceManager.GetString("Error_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp phải sớm hơn ngày hiện tại..
        /// </summary>
        public static string Error_DateOfIdentity {
            get {
                return ResourceManager.GetString("Error_DateOfIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại..
        /// </summary>
        public static string Error_DepartmentNotExists {
            get {
                return ResourceManager.GetString("Error_DepartmentNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại..
        /// </summary>
        public static string Error_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("Error_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng email không hợp lệ..
        /// </summary>
        public static string Error_EmailPatrern {
            get {
                return ResourceManager.GetString("Error_EmailPatrern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống..
        /// </summary>
        public static string Error_EmployeeCodeEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được bỏ trống..
        /// </summary>
        public static string Error_EmployeeDepartmentEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeDepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được phép để trống..
        /// </summary>
        public static string Error_EmployeeNameEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên quá dài, nên dưới 100 kí tự..
        /// </summary>
        public static string Error_EmployeeNameTooLong {
            get {
                return ResourceManager.GetString("Error_EmployeeNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được để trống..
        /// </summary>
        public static string Error_Empty {
            get {
                return ResourceManager.GetString("Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải kết thúc là một số..
        /// </summary>
        public static string Error_EndOfEmployeeCode {
            get {
                return ResourceManager.GetString("Error_EndOfEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng không hợp lệ..
        /// </summary>
        public static string Error_Format {
            get {
                return ResourceManager.GetString("Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu giới tính không hợp lệ..
        /// </summary>
        public static string Error_GenderNotFound {
            get {
                return ResourceManager.GetString("Error_GenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy mã mới, vui lòng tự điền..
        /// </summary>
        public static string Error_GetNewCode {
            get {
                return ResourceManager.GetString("Error_GetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tối đa: .
        /// </summary>
        public static string Error_MaxLength {
            get {
                return ResourceManager.GetString("Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tối thiểu:.
        /// </summary>
        public static string Error_MinLength {
            get {
                return ResourceManager.GetString("Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã bị sửa đổi bởi người khác, hãy thử lại sau..
        /// </summary>
        public static string Error_ModifiedAsync {
            get {
                return ResourceManager.GetString("Error_ModifiedAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bản ghi hiện tại..
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phải nằm trong khoảng: .
        /// </summary>
        public static string Error_Range {
            get {
                return ResourceManager.GetString("Error_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ..
        /// </summary>
        public static string Error_ValidateData {
            get {
                return ResourceManager.GetString("Error_ValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhân viên thành công!.
        /// </summary>
        public static string Success_InsertEmployee {
            get {
                return ResourceManager.GetString("Success_InsertEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa rõ.
        /// </summary>
        public static string Text_Unknown {
            get {
                return ResourceManager.GetString("Text_Unknown", resourceCulture);
            }
        }
    }
}
