//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web07.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web07.Core.Resources.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should be earlier than now..
        /// </summary>
        public static string Error_DateEarly {
            get {
                return ResourceManager.GetString("Error_DateEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birthday have to be earlier than now..
        /// </summary>
        public static string Error_DateOfBirth {
            get {
                return ResourceManager.GetString("Error_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of issuance of the citizen identity card must be earlier than the current date..
        /// </summary>
        public static string Error_DateOfIdentity {
            get {
                return ResourceManager.GetString("Error_DateOfIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is not exsist..
        /// </summary>
        public static string Error_DepartmentNotExists {
            get {
                return ResourceManager.GetString("Error_DepartmentNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate code..
        /// </summary>
        public static string Error_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("Error_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not formatted..
        /// </summary>
        public static string Error_EmailPatrern {
            get {
                return ResourceManager.GetString("Error_EmailPatrern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s code can&apos;t not be empty..
        /// </summary>
        public static string Error_EmployeeCodeEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s department can&apos;t not be empty..
        /// </summary>
        public static string Error_EmployeeDepartmentEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeDepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s name can&apos;t not be empty..
        /// </summary>
        public static string Error_EmployeeNameEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s name is too long, should be less than 100 characters..
        /// </summary>
        public static string Error_EmployeeNameTooLong {
            get {
                return ResourceManager.GetString("Error_EmployeeNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t be empty..
        /// </summary>
        public static string Error_Empty {
            get {
                return ResourceManager.GetString("Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code must be end with at least a digit..
        /// </summary>
        public static string Error_EndOfEmployeeCode {
            get {
                return ResourceManager.GetString("Error_EndOfEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Please contact MISA for supported..
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format is not valid..
        /// </summary>
        public static string Error_Format {
            get {
                return ResourceManager.GetString("Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data about gender are not valid..
        /// </summary>
        public static string Error_GenderNotFound {
            get {
                return ResourceManager.GetString("Error_GenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get new code, please fill out self..
        /// </summary>
        public static string Error_GetNewCode {
            get {
                return ResourceManager.GetString("Error_GetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length: .
        /// </summary>
        public static string Error_MaxLength {
            get {
                return ResourceManager.GetString("Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length: .
        /// </summary>
        public static string Error_MinLength {
            get {
                return ResourceManager.GetString("Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been modified by another, let try again late..
        /// </summary>
        public static string Error_ModifiedAsync {
            get {
                return ResourceManager.GetString("Error_ModifiedAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is not exists..
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should be in range:.
        /// </summary>
        public static string Error_Range {
            get {
                return ResourceManager.GetString("Error_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not validated..
        /// </summary>
        public static string Error_ValidateData {
            get {
                return ResourceManager.GetString("Error_ValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee successfully!.
        /// </summary>
        public static string Success_InsertEmployee {
            get {
                return ResourceManager.GetString("Success_InsertEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Text_Unknown {
            get {
                return ResourceManager.GetString("Text_Unknown", resourceCulture);
            }
        }
    }
}
